version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: django_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: storefront3
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: odoo18
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
